<?php

namespace RestoBundle\Repository;

/**
 * RestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestoRepository extends \Doctrine\ORM\EntityRepository
{
}
